# graphblas.apply

This example will go over how to use the `--graphblas-lower` pass from `graphblas-opt` to lower the `graphblas.apply` op.

Let’s first import some necessary modules and generate an instance of our JIT engine.

In [1]:
import mlir_graphblas
import mlir_graphblas.sparse_utils
import numpy as np

engine = mlir_graphblas.MlirJitEngine()

Here are the passes we'll use.

In [2]:
passes = [
    "--graphblas-lower",
    "--sparsification",
    "--sparse-tensor-conversion",
    "--linalg-bufferize",
    "--func-bufferize",
    "--tensor-bufferize",
    "--tensor-constant-bufferize",
    "--finalizing-bufferize",
    "--convert-linalg-to-loops",
    "--convert-scf-to-std",
    "--convert-memref-to-llvm",
    "--convert-std-to-llvm",
]

Similar to our examples using the GraphBLAS dialect, we'll need some helper functions to convert sparse tensors to dense tensors. 

In [3]:
mlir_text = """
#trait_densify_csr = {
  indexing_maps = [
    affine_map<(i,j) -> (i,j)>,
    affine_map<(i,j) -> (i,j)>
  ],
  iterator_types = ["parallel", "parallel"]
}

#trait_densify_vector = {
  indexing_maps = [
    affine_map<(i) -> (i)>,
    affine_map<(i) -> (i)>
  ],
  iterator_types = ["parallel"]
}

#CSR64 = #sparse_tensor.encoding<{
  dimLevelType = [ "dense", "compressed" ],
  dimOrdering = affine_map<(i,j) -> (i,j)>,
  pointerBitWidth = 64,
  indexBitWidth = 64
}>

#SparseVec64 = #sparse_tensor.encoding<{ 
    dimLevelType = [ "compressed" ], 
    pointerBitWidth = 64, 
    indexBitWidth = 64 
}>

func @csr_densify4x4(%argA: tensor<4x4xf64, #CSR64>) -> tensor<4x4xf64> {
  %output_storage = constant dense<0.0> : tensor<4x4xf64>
  %0 = linalg.generic #trait_densify_csr
    ins(%argA: tensor<4x4xf64, #CSR64>)
    outs(%output_storage: tensor<4x4xf64>) {
      ^bb(%A: f64, %x: f64):
        linalg.yield %A : f64
    } -> tensor<4x4xf64>
  return %0 : tensor<4x4xf64>
}

func @sparse_vector_densify4(%argA: tensor<4xf64, #SparseVec64>) -> tensor<4xf64> {
  %output_storage = constant dense<0.0> : tensor<4xf64>
  %0 = linalg.generic #trait_densify_vector
    ins(%argA: tensor<4xf64, #SparseVec64>)
    outs(%output_storage: tensor<4xf64>) {
      ^bb(%A: f64, %x: f64):
        linalg.yield %A : f64
    } -> tensor<4xf64>
  return %0 : tensor<4xf64>
}
"""

Let's compile our MLIR code. 

In [4]:
engine.add(mlir_text, passes)

['csr_densify4x4', 'sparse_vector_densify4']

## Overview of graphblas.apply

Here, we'll show how to use the `graphblas.apply` op. 

`graphblas.apply` takes 1 sparse tensor operand (either a CSR matrix, a CSC matrix, or a sparse vector), an optional [thunk](https://en.wikipedia.org/wiki/Thunk) operand, and an `apply_operator` attribute. 

The operator can be unary or binary. Binary operators require a thunk. The only supported binary operator is "min". Unary operators cannot take a thunk. The supported unary operators are "abs" and "minv" (i.e. [multiplicative inverse](https://en.wikipedia.org/wiki/Multiplicative_inverse)).

Using "minv" with integer types uses signed integer division and rounds towards zero. For example, the multiplicative inverse of -2 is 0.

`graphblas.apply` applies element-wise the function indicated by the `apply_operator` attribute to each element. The result will have the same type as the input tensor.

Here are some example uses of the `graphblas.apply` op:
```
%a = graphblas.apply %sparse_matrix, %thunk { apply_operator = "min" } : (tensor<?x?xf64, #CSR64>, f64) to tensor<?x?xf64, #CSR64>
%b = graphblas.apply %sparse_matrix { apply_operator = "abs" } : (tensor<?x?xf64, #CSC64>) to tensor<?x?xf64, #CSC64>
%c = graphblas.apply %sparse_vector, %thunk { apply_operator = "min" } : (tensor<?xf64, #CSR64>, f64) to tensor<?xf64, #CSR64>
```

Let's create an example input CSR matrix.

In [5]:
indices = np.array(
    [
        [0, 3],
        [1, 3],
        [2, 0],
        [3, 0],
    ],
    dtype=np.uint64,
)
values = np.array([111, 222, 333, 444], dtype=np.float64)
sizes = np.array([4, 4], dtype=np.uint64)
sparsity = np.array([False, True], dtype=np.bool8)

csr_matrix = mlir_graphblas.sparse_utils.MLIRSparseTensor(indices, values, sizes, sparsity)

In [6]:
dense_matrix = engine.csr_densify4x4(csr_matrix)

In [7]:
dense_matrix

array([[  0.,   0.,   0., 111.],
       [  0.,   0.,   0., 222.],
       [333.,   0.,   0.,   0.],
       [444.,   0.,   0.,   0.]])

Let's also create an example input sparse vector.

In [8]:
indices = np.array(
    [0, 3],
    dtype=np.uint64,
)
values = np.array([12, 34], dtype=np.float64)
sizes = np.array([4], dtype=np.uint64)
sparsity = np.array([True], dtype=np.bool8)

sparse_vector = mlir_graphblas.sparse_utils.MLIRSparseTensor(indices, values, sizes, sparsity)

In [9]:
dense_vector = engine.sparse_vector_densify4(sparse_vector)

In [10]:
dense_vector

array([12.,  0.,  0., 34.])

## graphblas.apply (Min)

Here, we'll clip the values of a sparse matrix to be no higher than a given limit.

In [11]:
mlir_text = """
#CSR64 = #sparse_tensor.encoding<{
  dimLevelType = [ "dense", "compressed" ],
  dimOrdering = affine_map<(i,j) -> (i,j)>,
  pointerBitWidth = 64,
  indexBitWidth = 64
}>

module {
    func @clip(%sparse_tensor: tensor<?x?xf64, #CSR64>, %limit: f64) -> tensor<?x?xf64, #CSR64> {
        %answer = graphblas.apply %sparse_tensor, %limit { apply_operator = "min" } : (tensor<?x?xf64, #CSR64>, f64) to tensor<?x?xf64, #CSR64>
        return %answer : tensor<?x?xf64, #CSR64>
    }
}
"""

In [12]:
engine.add(mlir_text, passes)

['clip']

In [13]:
sparse_result = engine.clip(csr_matrix, 200)

In [14]:
engine.csr_densify4x4(sparse_result)

array([[  0.,   0.,   0., 111.],
       [  0.,   0.,   0., 200.],
       [200.,   0.,   0.,   0.],
       [200.,   0.,   0.,   0.]])

The result looks sane. Let's verify that it has the same behavior as NumPy.

In [15]:
expected_result = dense_matrix.copy()
expected_result[expected_result>200] = 200
np.all(expected_result == engine.csr_densify4x4(sparse_result))

True

The way `graphblas.apply` works for CSC matrices and sparse vectors is similar. We'll leave exploring that as an exercise for the reader. 

## graphblas.apply (Unary Operators)

Here, we'll apply the absolute value function to each element of a sparse vector.

In [16]:
mlir_text = """
#SparseVec64 = #sparse_tensor.encoding<{ 
    dimLevelType = [ "compressed" ], 
    pointerBitWidth = 64, 
    indexBitWidth = 64 
}>

module {
    func @vector_abs(%sparse_tensor: tensor<?xf64, #SparseVec64>) -> tensor<?xf64, #SparseVec64> {
        %answer = graphblas.apply %sparse_tensor { apply_operator = "abs" } : (tensor<?xf64, #SparseVec64>) to tensor<?xf64, #SparseVec64>
        return %answer : tensor<?xf64, #SparseVec64>
    }
}
"""

In [17]:
engine.add(mlir_text, passes)

['vector_abs']

In [18]:
sparse_result = engine.vector_abs(sparse_vector)

In [19]:
engine.sparse_vector_densify4(sparse_result)

array([12.,  0.,  0., 34.])

The result looks sane. Let's verify that it has the same behavior as NumPy.

In [20]:
np.all(np.abs(dense_vector) == engine.sparse_vector_densify4(sparse_result))

True

The way `graphblas.apply` works for the other unary operators is similar. We'll leave exploring that as an exercise for the reader.